# Iris Shell - module ProGuard rules for :ui.
# Only rules that affect THIS module's release build belong here.
#
# Cross-module consumer rules belong in consumer-rules.pro for this module.

# Hilt ViewModel HiltModules are generated at compile time and referenced
# through reflection. Keep all ui module classes in release.
-keep class com.iris.irisshell.ui.** { *; }
-dontwarn com.iris.irisshell.ui.**

# CRITICAL: hilt_aggregated_deps classes are generated by Hilt KSP and only
# referenced via reflection by Dagger's ViewModelModule. Without this rule,
# R8 strips them, causing NoSuchFieldError / "Cannot create instance" for
# every @HiltViewModel in the ui module.
-keep class hilt_aggregated_deps.** { *; }
-keep class * extends dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$ViewModelFactoriesEntryPoint { *; }
